/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as poolSol from "./Pool.sol";
export type { poolSol };
export * as factories from "./factories";
export type { ERC20 } from "./ERC20.sol/ERC20";
export { ERC20__factory } from "./factories/ERC20.sol/ERC20__factory";
export type { IERC20 } from "./ERC20.sol/IERC20";
export { IERC20__factory } from "./factories/ERC20.sol/IERC20__factory";
export type { Pool } from "./Pool.sol/Pool";
export { Pool__factory } from "./factories/Pool.sol/Pool__factory";
